parameters:
#    acme_csunnso.example.class: Acme\CSUN\NSOBundle\Example

services:
#    acme_csunnso.example:
#        class: %acme_csunnso.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
